### ISSUE TITLE
Update version number

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/GSI-ncdiag#5]
The ncdiag version needs to be updated in the CMakeLists.txt script to match the current version (1.1.1).

**Comment by DavidHuber-NOAA** [comment]
@aerorahul @Hang-Lei-NOAA Should I update the version number to the current version so the 1.1.1 tag can be overwritten or should I update to 1.1.2 so a new tag can be created?

**Comment by aerorahul** [comment]
@DavidHuber-NOAA 
I think you can just update the current tag and re-tag it.
Let me know if you need assistance.

**Comment by DavidHuber-NOAA** [comment]
Great, thanks @aerorahul!
